### ISSUE TITLE
Possível imprecisão no conteúdo do header : Memória  virtual

### ISSUE THREAD

**Issue by pedroribeiro22** [Mendess2526/ResumosMIEI#6]
É referido que: "Idealmente os processos estariam todos em memória virtual mas isso não é possível". Não seria: "Idealmente os processos estariam todos em memória principal (RAM) mas isso não é possível".

Caso eu esteja errado, peço desde já desculpas.

**Comment by Mendess2526** [comment]
Fixed in #16
